export const NOTIFICATION_SETTINGS = "NOTIFICATION_SETTINGS";
export const ACCOUNT_SETTINGS = "ACCOUNT_SETTINGS";
export const GUEST_USER_PERMISSIONS = "GUEST_USER_PERMISSIONS";
export const GUEST_ACCOUNTS = "GuestAccounts";