// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorldPlants.Entities;

#nullable disable

namespace WorldPlants.Migrations
{
    [DbContext(typeof(WorldPlantsDbContext))]
    [Migration("20230705055307_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WorldPlants.Entities.ActiveTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.ToTable("ActiveTasks");
                });

            modelBuilder.Entity("WorldPlants.Entities.DefaultSite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanChangeHasRoof")
                        .HasColumnType("bit");

                    b.Property<int>("ColdPeriodMaxTemperature")
                        .HasColumnType("int");

                    b.Property<int>("ColdPeriodMinTemperature")
                        .HasColumnType("int");

                    b.Property<bool>("HasRoof")
                        .HasColumnType("bit");

                    b.Property<int>("Location")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WarmPeriodMaxTemperature")
                        .HasColumnType("int");

                    b.Property<int>("WarmPeriodMinTemperature")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DefaultSites");
                });

            modelBuilder.Entity("WorldPlants.Entities.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserSiteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserSiteId");

                    b.ToTable("Plants");
                });

            modelBuilder.Entity("WorldPlants.Entities.Space", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Spaces");
                });

            modelBuilder.Entity("WorldPlants.Entities.SunExposure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ForSiteType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SunScale")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SunExposures");
                });

            modelBuilder.Entity("WorldPlants.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SpaceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SpaceId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WorldPlants.Entities.UserSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CanAddPlants")
                        .HasColumnType("bit");

                    b.Property<bool>("CanEditPlants")
                        .HasColumnType("bit");

                    b.Property<bool>("CanFertilizePlants")
                        .HasColumnType("bit");

                    b.Property<bool>("CanMistPlants")
                        .HasColumnType("bit");

                    b.Property<bool>("CanMovePlants")
                        .HasColumnType("bit");

                    b.Property<bool>("CanRemovePlants")
                        .HasColumnType("bit");

                    b.Property<bool>("CanRepotPlants")
                        .HasColumnType("bit");

                    b.Property<bool>("CanWaterPlants")
                        .HasColumnType("bit");

                    b.Property<bool>("ReceiveEmails")
                        .HasColumnType("bit");

                    b.Property<bool>("ReceiveSms")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("WorldPlants.Entities.UserSite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanChangeHasRoof")
                        .HasColumnType("bit");

                    b.Property<int>("ColdPeriodMaxTemperature")
                        .HasColumnType("int");

                    b.Property<int>("ColdPeriodMinTemperature")
                        .HasColumnType("int");

                    b.Property<bool>("HasRoof")
                        .HasColumnType("bit");

                    b.Property<int>("Location")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SpaceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SunExposureId")
                        .HasColumnType("int");

                    b.Property<int>("WarmPeriodMaxTemperature")
                        .HasColumnType("int");

                    b.Property<int>("WarmPeriodMinTemperature")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpaceId");

                    b.HasIndex("SunExposureId");

                    b.ToTable("UserSites");
                });

            modelBuilder.Entity("WorldPlants.Entities.ActiveTask", b =>
                {
                    b.HasOne("WorldPlants.Entities.Plant", "Plant")
                        .WithMany("ActiveTasks")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("WorldPlants.Entities.Plant", b =>
                {
                    b.HasOne("WorldPlants.Entities.UserSite", "UserSite")
                        .WithMany("Plants")
                        .HasForeignKey("UserSiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserSite");
                });

            modelBuilder.Entity("WorldPlants.Entities.User", b =>
                {
                    b.HasOne("WorldPlants.Entities.Space", "Space")
                        .WithMany("Users")
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Space");
                });

            modelBuilder.Entity("WorldPlants.Entities.UserSettings", b =>
                {
                    b.HasOne("WorldPlants.Entities.User", "User")
                        .WithOne("UserSettings")
                        .HasForeignKey("WorldPlants.Entities.UserSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WorldPlants.Entities.UserSite", b =>
                {
                    b.HasOne("WorldPlants.Entities.Space", "Space")
                        .WithMany("UserSites")
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorldPlants.Entities.SunExposure", "SunExposure")
                        .WithMany()
                        .HasForeignKey("SunExposureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Space");

                    b.Navigation("SunExposure");
                });

            modelBuilder.Entity("WorldPlants.Entities.Plant", b =>
                {
                    b.Navigation("ActiveTasks");
                });

            modelBuilder.Entity("WorldPlants.Entities.Space", b =>
                {
                    b.Navigation("UserSites");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("WorldPlants.Entities.User", b =>
                {
                    b.Navigation("UserSettings")
                        .IsRequired();
                });

            modelBuilder.Entity("WorldPlants.Entities.UserSite", b =>
                {
                    b.Navigation("Plants");
                });
#pragma warning restore 612, 618
        }
    }
}
